title: Gabriel Nascarella Hishida's github.io website
url: "https://gabrielnhn.github.io"
# baseurl: ""
newbaseurl: /

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "/"
 - name: "Contact"
   link: "contact"
