title: Gabriel Hishida's website
url: "https://gabrielnhn.github.io"
# baseurl: ""
newbaseurl: /

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Resume"
   link: "/cv-may-2023.pdf"
 - name: "Contact"
   link: "contact"
